### ISSUE TITLE
Configuration with name 'compileOnly' not found.

### ISSUE THREAD

**Issue by Shan1024** [hurricup/gradle-grammar-kit-plugin#7]
I get the following error on gradle 4.5.1. Any idea on how to fix this?

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'ballerina-idea-plugin'.
> Configuration with name 'compileOnly' not found.
```

**Comment by hurricup** [comment]
nope, need to investigate.

**Comment by hurricup** [comment]
Can i see a build script?

**Comment by Shan1024** [comment]
@hurricup - Seems like it was due to an issue in the build script which is not related to this plugin. Sorry about the noise.
